import {
  Blockchain,
  verifyAddress,
} from '@lombard.finance/btc-deposit-addresses';
import axios from 'axios';
import { getApiConfig } from '../../common/api-config';
import { getChainNameById } from '../../common/blockchain-identifier';
import { ChainId, SolanaChain, SuiChain } from '../../common/chains';
import { IEnvParam } from '../../common/parameters';
import { getErrorMessage } from '../../utils/err';
import {
  VERIFIABLE_CHAINS,
  getDepositBtcAddresses,
} from '../getDepositBtcAddress';

/**
 * The address wich will be returned if the provided EVM address is sanctioned.
 */
export const SANCTIONED_ADDRESS = 'sanctioned_address';
const ADDRESS_URL = 'api/v1/address/generate';
const SANCTIONS_MESSAGE = 'destination address is under sanctions';

interface IGenerateNewAddressResponse {
  address: string;
}

export interface IGenerateDepositBtcAddressParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The destination chain ID where LBTC will be claimed.
   */
  chainId: ChainId | SuiChain | SolanaChain;
  /**
   * The signature of the address. The signature is generated by signing the address using EVM wallet.
   */
  signature: string;
  /**
   * The typed data object used to generate the signature if using a network fee authorization signature.
   */
  eip712Data?: string;
  /**
   * The captcha token.
   */
  captchaToken?: string;
  /**
   * The referrer code.
   */
  referrerCode?: string;
  /**
   * The referral ID.
   */
  partnerId?: string;
  /**
   * The typed data object used to generate the signature if using a stake and bake feature.
   */
  signatureData?: string;
}

/**
 * Generates a BTC deposit address.
 *
 * If the provided EVM address is sanctioned, the function will return the `SANCTIONED_ADDRESS`.
 *
 * @param {IGenerateDepositBtcAddressParams} parameters - The parameters for generating the deposit address.
 * @param {string} parameters.address - The destination EVM user address where LBTC will be claimed.
 * @param {ChainId} parameters.chainId - The destination chain ID where LBTC will be claimed.
 * @param {string} parameters.signature - The signature of the address. The signature is generated by signing the address using EVM wallet.
 * @param {string} parameters.eip712Data - The typed data object used to generate the signature if using a network fee authorization signature.
 * @param {string} parameters.captchaToken - The captcha token.
 * @param {string} parameters.referrerCode - The referrer code.
 * @param {string} parameters.partnerId - The partner ID.
 * @param {string} parameters.signatureData - The typed data object used to generate the signature if using a stake and bake feature.
 * @param {Env} parameters.env - The optional environment identifier.
 *
 * @returns {Promise<string>} The generated deposit address.
 */
export async function generateDepositBtcAddress({
  address,
  chainId,
  signature,
  eip712Data,
  env,
  referrerCode,
  partnerId,
  captchaToken,
  signatureData,
}: IGenerateDepositBtcAddressParams): Promise<string> {
  const { baseApiUrl } = getApiConfig(env);
  const toChain = getChainNameById(chainId);

  const requestParams = {
    to_address: address,
    to_address_signature: signature,
    to_chain: toChain,
    partner_id: partnerId,
    nonce: 0,
    captcha: captchaToken,
    referrer_code: referrerCode,
    eip_712_data: eip712Data,
    sb_signature_data: signatureData,
  };

  try {
    const { data } = await axios.post<IGenerateNewAddressResponse>(
      ADDRESS_URL,
      requestParams,
      { baseURL: baseApiUrl },
    );

    const depositAddress = data.address;

    const confirmed = (
      await getDepositBtcAddresses({
        address,
        chainId,
        env,
        partnerId,
      })
    ).find(a => a.btc_address === depositAddress);

    if (!confirmed) {
      throw new Error(
        `Unable to confirm the BTC deposits address: ${depositAddress}. Try again or check if the address exists via 'getDepositBtcAddress' function.`,
      );
    }

    const canVerify = Object.keys(VERIFIABLE_CHAINS).includes(String(chainId));
    if (canVerify) {
      const blockchain = VERIFIABLE_CHAINS[chainId] as Blockchain;
      const [verified, calculated] = verifyAddress(
        confirmed.btc_address,
        confirmed.deposit_metadata.nonce || 0,
        confirmed.deposit_metadata.referral || '',
        address,
        blockchain,
      );
      if (!verified) {
        throw new Error(
          `The BTC deposit address ${confirmed.btc_address} is not valid. The deposit address is not the same as expected (${calculated})`,
        );
      }
    } else {
      console.warn(
        `The BTC deposit address ${depositAddress} cannot be verified. Only the following destination chains are verifiable: ${Object.keys(VERIFIABLE_CHAINS).join(', ')}`,
      );
    }

    return confirmed.btc_address;
  } catch (error) {
    const errorMsg = getErrorMessage(error);

    if (isSanctioned(errorMsg)) {
      return SANCTIONED_ADDRESS;
    }
    throw new Error(errorMsg);
  }
}

function isSanctioned(errorMsg: string): boolean {
  return errorMsg.includes(SANCTIONS_MESSAGE);
}
