import axios from 'axios';
import { getApiConfig } from '../../common/api-config';
import {
  BlockchainIdentifier,
  getChainNameById,
} from '../../common/blockchain-identifier';
import type {
  ChainId,
  SolanaChain,
  StarknetChainId,
  SuiChain,
} from '../../common/chains';
import type { IEnvParam } from '../../common/parameters';
import {
  getErrorMessage,
  TokenContractAddressNotFoundError,
} from '../../utils/err';
import { AddressKind, Token } from '../../tokens/token-addresses';
import { getTokenContractInfo } from '../../tokens/tokens';
import { Address, pad } from 'viem';

/**
 * The address which will be returned if the provided EVM address is sanctioned.
 */
export const SANCTIONED_ADDRESS = 'sanctioned_address';
const ADDRESS_URL = 'api/v1/address/generate';
const SANCTIONS_MESSAGE = 'destination address is under sanctions';

interface IGenerateNewAddressResponse {
  address: string;
}

export interface IGenerateDepositBtcAddressParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The intended destination token, defaults to LBTC.
   */
  token?: Token;
  /**
   * The destination chain ID where LBTC will be claimed.
   */
  chainId: ChainId | SuiChain | SolanaChain | StarknetChainId;
  /**
   * The signature of the address. The signature is generated by signing the address using EVM wallet.
   */
  signature: string;
  /**
   * The typed data object used to generate the signature if using a network fee authorization signature.
   */
  eip712Data?: string;
  /**
   * The captcha token.
   */
  captchaToken?: string;
  /**
   * The referrer code.
   */
  referrerCode?: string;
  /**
   * The referral ID.
   */
  partnerId?: string;
  /**
   * The typed data object used to generate the signature if using a stake and bake feature.
   */
  signatureData?: string;

  /** The pubKey required for starknet addresses signatures. */
  pubKey?: string;
}

const EXTRA_PARAMS_TOKENS = [Token.LBTC, Token.BTCK, Token.BTCb];
const SUPPORTED_TOKENS = [Token.LBTC, Token.BTCK, Token.BTCb];

/**
 * Generates a BTC deposit address.
 *
 * If the provided EVM address is sanctioned, the function will return the `SANCTIONED_ADDRESS`.
 *
 * @param {IGenerateDepositBtcAddressParams} parameters - The parameters for generating the deposit address.
 * @param {string} parameters.address - The destination EVM user address where LBTC will be claimed.
 * @param {ChainId} parameters.chainId - The destination chain ID where LBTC will be claimed.
 * @param {string} parameters.signature - The signature of the address. The signature is generated by signing the address using EVM wallet.
 * @param {string} parameters.eip712Data - The typed data object used to generate the signature if using a network fee authorization signature.
 * @param {string} parameters.captchaToken - The captcha token.
 * @param {string} parameters.referrerCode - The referrer code.
 * @param {string} parameters.partnerId - The partner ID.
 * @param {string} parameters.signatureData - The typed data object used to generate the signature if using a stake and bake feature.
 * @param {Env} parameters.env - The optional environment identifier.
 *
 * @returns {Promise<string>} The generated deposit address.
 */
export async function generateDepositBtcAddress({
  address,
  token = Token.LBTC,
  chainId,
  signature,
  eip712Data,
  env,
  referrerCode,
  partnerId,
  captchaToken,
  signatureData,
  pubKey,
}: IGenerateDepositBtcAddressParams): Promise<string> {
  const { baseApiUrl } = getApiConfig(env);
  const toChain = getChainNameById(chainId);

  if (!SUPPORTED_TOKENS.includes(token)) {
    throw new Error(`Unsupported token: ${token}`);
  }

  let additionalParams = {};
  if (toChain === BlockchainIdentifier.starknet) {
    address = pad(address as Address, { size: 32 });
    if (!pubKey) {
      throw new Error('Missing parameter: pubKey');
    }

    additionalParams = {
      public_key: pubKey,
    };
  }

  // TODO: Refactor
  // //primaryType: 'feeApproval', - NETWORK FEE
  // //primaryType: 'Permit', - STAKE AND BAKE
  // type generationFrom =
  //   | 'network-fee'
  //   | 'stake-and-bake'
  //   | 'destination-address';

  // let generation: generationFrom = 'destination-address';
  // if (signatureData != null) {
  //   try {
  //     const typedData = JSON.parse(signatureData);
  //     if (typedData?.primaryType === 'feeApproval') {
  //       generation = 'network-fee';
  //     } else if (typedData?.primaryType === 'Permit') {
  //       generation = 'stake-and-bake';
  //     }
  //   } catch {
  //     // NOOP
  //   }
  // }

  /**
   * The deposit address generation requires additional fields for tokens other
   * than LBTC.
   */
  let tokenDataParams = {};
  try {
    if (
      EXTRA_PARAMS_TOKENS.includes(token) &&
      // FIXME: Refactor in order to pull in all token addresses from all supported networks to the sdk-common package.
      // FIXME: Then remove this clause prior two token model.
      !(
        [
          BlockchainIdentifier.sui,
          BlockchainIdentifier.solana,
          BlockchainIdentifier.starknet,
        ] as BlockchainIdentifier[]
      ).includes(toChain)
    ) {
      const tokenContractInfo = await getTokenContractInfo(
        token,
        chainId as ChainId,
        env,
        AddressKind.Adapter,
      );
      tokenDataParams = {
        token_address: tokenContractInfo.address,
      };
    }
  } catch (err) {
    if (
      err instanceof Error &&
      err instanceof TokenContractAddressNotFoundError &&
      EXTRA_PARAMS_TOKENS.includes(token)
    ) {
      throw new Error(
        `Unable to generate BTC deposit address for given token: ${token} in ${chainId}, reason: ${err.message}`,
      );
    }
  }

  // TODO: Refactor
  // const signatureDataRequestParams =
  //   generation === 'network-fee'
  //     ? {
  //         eip_712_data: signatureData,
  //       }
  //     : generation === 'stake-and-bake'
  //       ? { sb_signature_data: signatureData }
  //       : {};

  const requestParams = {
    to_address: address,
    to_address_signature: signature,
    to_chain: toChain,
    partner_id: partnerId,
    nonce: 0,
    captcha: captchaToken,
    referrer_code: referrerCode,
    eip_712_data: eip712Data,
    sb_signature_data: signatureData,
    ...tokenDataParams,
    ...additionalParams,
  };

  try {
    const { data } = await axios.post<IGenerateNewAddressResponse>(
      ADDRESS_URL,
      requestParams,
      { baseURL: baseApiUrl },
    );

    return data.address;
  } catch (error) {
    const errorMsg = getErrorMessage(error);

    if (isSanctioned(errorMsg)) {
      return SANCTIONED_ADDRESS;
    }
    throw new Error(errorMsg);
  }
}

function isSanctioned(errorMsg: string): boolean {
  return errorMsg.includes(SANCTIONS_MESSAGE);
}
