import axios from 'axios';
import { IEnvParam } from '../../common/parameters';
import { SuiChain, ChainId } from '../../common/chains';
import { getErrorMessage } from '../../utils/err';
import { getApiConfig } from '../../common/api-config';
import { getChainNameById } from '../../common/blockchain-identifier';

/**
 * The address wich will be returned if the provided EVM address is sanctioned.
 */
export const SANCTIONED_ADDRESS = 'sanctioned_address';
const ADDRESS_URL = 'api/v1/address/generate';
const SANCTIONS_MESSAGE = 'destination address is under sanctions';

interface IGenerateNewAddressResponse {
  address: string;
}

export interface IGenerateDepositBtcAddressParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The destination chain ID where LBTC will be claimed.
   */
  chainId: ChainId | SuiChain;
  /**
   * The signature of the address. The signature is generated by signing the address using EVM wallet.
   */
  signature: string;
  /**
   * The typed data object used to generate the signature if using a network fee authorization signature.
   */
  eip712Data?: string;
  /**
   * The captcha token.
   */
  captchaToken?: string;
  /**
   * The referrer code.
   */
  referrerCode?: string;
  /**
   * The referral ID.
   */
  partnerId?: string;
  /**
   * The typed data object used to generate the signature if using a stake and bake feature.
   */
  signatureData?: string;
}

/**
 * Generates a BTC deposit address.
 *
 * If the provided EVM address is sanctioned, the function will return the `SANCTIONED_ADDRESS`.
 *
 * @param {IGenerateDepositBtcAddressParams} parameters - The parameters for generating the deposit address.
 * @param {string} parameters.address - The destination EVM user address where LBTC will be claimed.
 * @param {ChainId} parameters.chainId - The destination chain ID where LBTC will be claimed.
 * @param {string} parameters.signature - The signature of the address. The signature is generated by signing the address using EVM wallet.
 * @param {string} parameters.eip712Data - The typed data object used to generate the signature if using a network fee authorization signature.
 * @param {string} parameters.captchaToken - The captcha token.
 * @param {string} parameters.referrerCode - The referrer code.
 * @param {string} parameters.partnerId - The partner ID.
 * @param {string} parameters.signatureData - The typed data object used to generate the signature if using a stake and bake feature.
 * @param {Env} parameters.env - The optional environment identifier.
 *
 * @returns {Promise<string>} The generated deposit address.
 */
export async function generateDepositBtcAddress({
  address,
  chainId,
  signature,
  eip712Data,
  env,
  referrerCode,
  partnerId,
  captchaToken,
  signatureData,
}: IGenerateDepositBtcAddressParams): Promise<string> {
  const { baseApiUrl } = getApiConfig(env);
  const toChain = getChainNameById(chainId);

  const requestParams = {
    to_address: address,
    to_address_signature: signature,
    to_chain: toChain,
    partner_id: partnerId,
    nonce: 0,
    captcha: captchaToken,
    referrer_code: referrerCode,
    eip_712_data: eip712Data,
    sb_signature_data: signatureData,
  };

  try {
    const { data } = await axios.post<IGenerateNewAddressResponse>(
      ADDRESS_URL,
      requestParams,
      { baseURL: baseApiUrl },
    );

    return data.address;
  } catch (error) {
    const errorMsg = getErrorMessage(error);

    if (isSanctioned(errorMsg)) {
      return SANCTIONED_ADDRESS;
    }
    throw new Error(errorMsg);
  }
}

function isSanctioned(errorMsg: string): boolean {
  return errorMsg.includes(SANCTIONS_MESSAGE);
}
