import * as SILO_VAULT_SPENDER_ABI from "./SILO_VAULT_SPENDER_ABI.json";
import * as VEDA_VAULT_SPENDER_ABI from "./VEDA_VAULT_SPENDER_ABI.json";

export { SILO_VAULT_SPENDER_ABI, VEDA_VAULT_SPENDER_ABI };
