import axios from "axios";

import { getApiConfig } from "../../common/api-config";
import { IEnvParam } from "../../common/parameters";
import { getErrorMessage } from "../../utils/err";

const URL = "api/v1/referral-system/referrer/";

export interface ISetReferralParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The signature of the address. The signature is generated by signing the address using wallet.
   * Use `signTermsOfService` or `signLbtcDestinationAddr` functions.
   */
  signature: string;
  /**
   * The captcha token.
   */
  referrerCode: string;
  /**
   * The typed data object used to generate the signature if using a network fee authorization signature.
   */
  eip712Data?: string;
  /**
   * The public key (required for Starknet).
   */
  pubKey?: string;
}

/**
 * Set a referral code.
 *
 * @param {ISetReferralParams} The parameters for set referral.
 * @returns {Promise<void>} Nothing.
 * @exception {Error}
 */
export async function setReferral({
  address,
  signature,
  eip712Data,
  referrerCode,
  pubKey,
  env,
}: ISetReferralParams): Promise<void> {
  const { baseApiUrl } = getApiConfig(env);

  const requestParams = {
    referrer_code: referrerCode,
    signature,
    signature_typed_data: eip712Data,
    ...(pubKey && { public_key: pubKey }),
  };

  try {
    await axios.post(`${URL}${address}`, requestParams, {
      baseURL: baseApiUrl,
    });

    return undefined;
  } catch (error) {
    const errorMsg = getErrorMessage(error);
    throw new Error(errorMsg);
  }
}
