import axios from 'axios';
import { IEnvParam } from '../../common/types/internalTypes';
import { TChainId } from '../../common/types/types';
import { getApiConfig } from '../apiConfig';
import { getChainNameById } from '../utils/getChainNameById';

const ADDRESS_URL = 'api/v1/address';

interface IGenerateNewAddressResponse {
  address: string;
}

export interface IGenerateDepositBtcAddressParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The destination chain ID where LBTC will be claimed.
   */
  chainId: TChainId;
  /**
   * The signature of the address. The signature is generated by signing the address using EVM wallet.
   */
  signature: string;
  /**
   * The referral ID.
   */
  referralId?: string;
}

/**
 * Generates a BTC deposit address.
 * @param {IGenerateDepositBtcAddressParams} params - The parameters for generating the deposit address.
 * @returns {Promise<string>} The generated deposit address.
 */
export async function generateDepositBtcAddress({
  address,
  chainId,
  signature,
  referralId,
  env,
}: IGenerateDepositBtcAddressParams): Promise<string> {
  const { depositAddrApiUrl } = getApiConfig(env);
  const toChain = getChainNameById(chainId);

  const requestParams = {
    to_address: address,
    to_address_signature: signature,
    to_chain: toChain,
    referral_id: referralId,
    nonce: 0,
  };

  const { data } = await axios.post<IGenerateNewAddressResponse>(
    ADDRESS_URL,
    requestParams,
    {
      baseURL: depositAddrApiUrl,
    },
  );

  return data.address;
}
