/**
 * Strategy module - Lombard DeFi Vault Strategy (Bitcoin Stretch).
 *
 * Multi-asset, async-redeem vault contract that issues ERC-20 shares.
 * Distinct from the Veda Teller-based BTCe vault exposed under
 * `@lombard.finance/sdk/vaults`; do not conflate the two.
 *
 * Import from `'@lombard.finance/sdk/strategies'`.
 */

export {
  depositStrategy,
  type DepositStrategyParameters,
  findStaticDepositAsset,
  getDefaultStrategyAddress,
  getStrategyDepositAssets,
  type GetStrategyDepositAssetsParameters,
  getStrategyNavHistory,
  type GetStrategyNavHistoryParameters,
  getStrategyPendingRedeem,
  type GetStrategyPendingRedeemParameters,
  getStrategyPosition,
  type GetStrategyPositionParameters,
  getStrategyRatesHistory,
  type GetStrategyRatesHistoryParameters,
  getStrategyShards,
  type GetStrategyShardsParameters,
  getStrategyState,
  type GetStrategyStateParameters,
  getUserActivityFeed,
  type GetUserActivityFeedParameters,
  getUserPosition,
  type GetUserPositionParameters,
  getUserPositionHistory,
  type GetUserPositionHistoryParameters,
  getUserWithdrawals,
  type GetUserWithdrawalsParameters,
  type IRequestStrategyRedeemResult,
  isLombardStrategyChain,
  type IStrategyAllocationRow,
  type IStrategyBaseAsset,
  type IStrategyConfigResponse,
  type IStrategyDepositAsset,
  type IStrategyDepositAssetStatic,
  type IStrategyFeeConfig,
  type IStrategyNavSnapshot,
  type IStrategyPendingRedeem,
  type IStrategyPosition,
  type IStrategyRatesSnapshot,
  type IStrategyShards,
  type IStrategyState,
  type IStrategyUserActivityEntry,
  type IStrategyUserPosition,
  type IStrategyUserPositionSnapshot,
  type IStrategyUserWithdrawalRequest,
  LOMBARD_STRATEGY,
  LOMBARD_STRATEGY_CHAINS,
  LOMBARD_STRATEGY_CONTRACTS,
  LOMBARD_STRATEGY_DECIMALS,
  LOMBARD_STRATEGY_DEPOSIT_ASSETS,
  type LombardStrategyChain,
  previewStrategyDeposit,
  type PreviewStrategyDepositParameters,
  requestStrategyRedeem,
  type RequestStrategyRedeemParameters,
  UnauthorizedWalletJwtError,
} from '../strategies';
