/**
 * Strategy module - Lombard DeFi Vault Strategy (BTCoc).
 *
 * Multi-asset, async-redeem vault contract that issues ERC-20 shares.
 * Distinct from the Veda Teller-based BTCe vault exposed under
 * `@lombard.finance/sdk/vaults`; do not conflate the two.
 *
 * Import from `'@lombard.finance/sdk/strategies'`.
 */

export {
  DEFAULT_STRATEGY_ID,
  depositStrategy,
  type DepositStrategyParameters,
  findStaticDepositAsset,
  getStrategyDefinition,
  getStrategyDeployment,
  getStrategyDepositAssets,
  type GetStrategyDepositAssetsParameters,
  getStrategyNavHistory,
  type GetStrategyNavHistoryParameters,
  getStrategyPendingRedeem,
  type GetStrategyPendingRedeemParameters,
  getStrategyPosition,
  type GetStrategyPositionParameters,
  getStrategyRatesHistory,
  type GetStrategyRatesHistoryParameters,
  getStrategyShards,
  type GetStrategyShardsParameters,
  getStrategyState,
  type GetStrategyStateParameters,
  getStrategyUserPosition,
  getUserActivityFeed,
  type GetUserActivityFeedParameters,
  getUserPositionHistory,
  type GetUserPositionHistoryParameters,
  type GetUserPositionParameters,
  getUserWithdrawals,
  type GetUserWithdrawalsParameters,
  type IRequestStrategyRedeemResult,
  type IStrategyAllocationRow,
  type IStrategyBaseAsset,
  type IStrategyConfigResponse,
  type IStrategyDepositAsset,
  type IStrategyDepositAssetStatic,
  type IStrategyFeeConfig,
  type IStrategyNavSnapshot,
  type IStrategyPendingRedeem,
  type IStrategyPosition,
  type IStrategyRatesSnapshot,
  type IStrategyShards,
  type IStrategyState,
  type IStrategyUserActivityEntry,
  type IStrategyUserActivityFeed,
  type IStrategyUserPosition,
  type IStrategyUserPositionSnapshot,
  type IStrategyUserWithdrawalRequest,
  previewStrategyDeposit,
  type PreviewStrategyDepositParameters,
  requestStrategyRedeem,
  type RequestStrategyRedeemParameters,
  type ResolvedStrategy,
  resolveStrategy,
  STRATEGIES,
  type StrategyBaseParameters,
  type StrategyChainDeployment,
  type StrategyDefinition,
  type StrategyId,
  type StrategyReadParameters,
  type StrategyWriteParameters,
  UnauthorizedWalletJwtError,
} from '../strategies';
