import axios from 'axios';
import { IEnvParam } from '../../common/types/internalTypes';
import { getErrorMessage } from '../../common/utils/getErrorMessage';
import { getApiConfig } from '../apiConfig';

const URL = 'api/v1/referral-system/referrer/';

interface ISetReferrerResponse {}

export interface ISetReferralParams extends IEnvParam {
  /**
   * The destination EVM user address where LBTC will be claimed.
   */
  address: string;
  /**
   * The signature of the address. The signature is generated by signing the address using EVM wallet.
   */
  signature: string;
  /**
   * The typed data object used to generate the signature if using a network fee authorization signature.
   */
  eip712Data: string;
  /**
   * The captcha token.
   */
  referrerCode: string;
}

/**
 * Set a referral code.
 *
 * @param {ISetReferralParams} The parameters for set referral.
 * @returns {Promise<void>} Nothing.
 * @exception {Error}
 */
export async function setReferral({
  address,
  signature,
  eip712Data,
  referrerCode,
  env,
}: ISetReferralParams): Promise<void> {
  const { baseApiUrl } = getApiConfig(env);

  const requestParams = {
    referrer_code: referrerCode,
    signature,
    signature_typed_data: eip712Data,
  };

  try {
    await axios.post<ISetReferrerResponse>(`${URL}${address}`, requestParams, {
      baseURL: baseApiUrl,
    });

    return undefined;
  } catch (error) {
    const errorMsg = getErrorMessage(error);
    throw new Error(errorMsg);
  }
}
