name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.AWS_ECR_REGISTRY }}/library/alpine-git-node-aws:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ci
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref || github.sha }}

      - name: Allow Git to access repo
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: License policy check
        run: yarn licenses:check

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:required
